# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-12-26 19:21+0330\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: .\config\settings\language.py:20
msgid "English"
msgstr ""

#: .\config\settings\language.py:21
msgid "Persian"
msgstr ""

#: .\config\urls.py:39
msgid "admin/"
msgstr ""

#: .\fixplus\common\apis.py:24
msgid "Invalid permission."
msgstr "دسترسی به درستی تنظیم نشده است."

#: .\fixplus\common\apis.py:31
msgid "You do not have permission to perform this action."
msgstr "دسترسی لازم را ندارید."

#: .\fixplus\common\permissions.py:13
msgid "You not allowed to use this method, should be verified mobile."
msgstr "شما دسترسی لازم را ندارید، ابتدا شماره موبایل خود را وریفای کنید."

#: .\fixplus\common\permissions.py:20 .\fixplus\common\permissions.py:27
#: .\fixplus\common\permissions.py:33 .\fixplus\common\permissions.py:39
#: .\fixplus\common\permissions.py:48
msgid "You not allowed to use this method."
msgstr "شما دسترسی لازم را ندارید."

#: .\fixplus\customer\serializers\serializers.py:48
#: .\fixplus\job\serializers\technician_for_job.py:26
#: .\fixplus\user\serializers\auth.py:18 .\fixplus\user\serializers\auth.py:39
#: .\fixplus\user\serializers\auth.py:60 .\fixplus\user\serializers\user.py:29
msgid ""
"Mobile number must start with '00' or '+' and contain only digits after that."
msgstr "شماره موبایل باید با 00 یا + شروع شود."

#: .\fixplus\job\apis\determine.py:34
msgid "The status of the referred service was successfully determined."
msgstr "وضعیت کار ارحاع شده با موفقیت تغییر کرد."

#: .\fixplus\job\apis\job.py:65
msgid "Successfully placed in the assign queue."
msgstr "با موفقیت در صف ارحاع قرار گرفت."

#: .\fixplus\job\apis\referred.py:58 .\fixplus\job\apis\referred.py:68
#: .\fixplus\parametric\apis\apis.py:53 .\fixplus\parametric\apis\apis.py:114
#: .\fixplus\parametric\apis\apis.py:165
#, fuzzy
#| msgid "You not allowed to use this method."
msgid "You are not allowed to use this method."
msgstr "شما دسترسی لازم را ندارید."

#: .\fixplus\job\apis\referred.py:85
msgid "Successfully referred to technician."
msgstr "با موفقیت به تکنسین ارجاع داده شد."

#: .\fixplus\job\serializers\job.py:64 .\fixplus\job\serializers\referred.py:86
#: .\fixplus\job\serializers\referred.py:113
#, fuzzy
#| msgid ""
#| "Mobile number must start with '00' or '+' and contain only digits after "
#| "that."
msgid ""
"Phone number must start with '00' or '+' and contain only digits after that."
msgstr "شماره موبایل باید با 00 یا + شروع شود."

#: .\fixplus\job\services\determine.py:19
#: .\fixplus\job\services\determine.py:20
#: .\fixplus\job\services\determine.py:24
msgid "You do not have access to do this."
msgstr "شما دسترسی لازم را ندارید."

#: .\fixplus\job\services\determine.py:21
msgid "You must enter the reason for rejection."
msgstr "دلیل رد کردن را باید وارد کنید."

#: .\fixplus\job\services\referred.py:20
msgid "This service has already been referred."
msgstr "این کار قبلا ارجاع داده شده است."

#: .\fixplus\parametric\selectors\selectors.py:11
msgid "The configuration parameter was not found, please contact the admin."
msgstr "پارامتر تنظیمات پیدا نشد، لطفا با ادمین تماس بگیرید."

#: .\fixplus\upload\selectors.py:11
msgid "Media file not found."
msgstr "فایل مدیا پیدا نشد، ایدی ارسالی اشتباه است."

#: .\fixplus\user\apis\auth\resend_otp_code.py:26
msgid "User with this mobile not found."
msgstr "کاربری با این شماره موبایل پیدا نشد"

#: .\fixplus\user\apis\auth\resend_otp_code.py:41
#: .\fixplus\user\apis\auth\sign_in_up.py:45
msgid "A verification code has been send to your mobile number."
msgstr "یک کد اعتبارسنجی به شماره موبایل شما پیامک شد."

#: .\fixplus\user\apis\auth\resend_otp_code.py:44
#: .\fixplus\user\apis\auth\sign_in_up.py:49
msgid "2 minutes must have passed since the last sms was sent."
msgstr "دو دقیقه باید از ارسال کد اعتبارسنحی قبلی بگذرد."

#: .\fixplus\user\apis\user\register.py:21
msgid "The request was sent successfully."
msgstr "درخواست با موفقیت ارسال شد."

#: .\fixplus\user\selectors\profile.py:13
msgid "Profile does not exist"
msgstr "پروفایل پیدا نشد."

#: .\fixplus\user\selectors\user.py:21 .\fixplus\user\selectors\user.py:92
msgid "User not found."
msgstr "کاربر پیدا نشد."

#: .\fixplus\user\selectors\user.py:95 .\fixplus\user\selectors\user.py:96
msgid "User not verified, please verified mobile first."
msgstr ""
"حساب کاربری شما وریفای نشده، لطفا ابتدا شماره موبایل خود را وریفای کنید."

#: .\fixplus\user\services\group.py:10 .\fixplus\user\services\group.py:18
msgid "One or more groups do not exist."
msgstr "یک یا چند گروه یافت نشد."

#: .\fixplus\user\services\permission.py:9
#: .\fixplus\user\services\permission.py:17
#: .\fixplus\user\services\permission.py:25
#: .\fixplus\user\services\permission.py:33
msgid "One or more permissions do not exist."
msgstr "یک یا چند مجوز پیدا نشد."

#: .\fixplus\user\services\register.py:10
msgid "You have already registered."
msgstr "شما قبلا ثبت نام کرده اید."

#: .\fixplus\user\services\register.py:11
msgid "Your request has already been rejected by the admin."
msgstr "درخواست شما قبلا توسط مدیر رد شده است."

#: .\fixplus\user\services\register.py:12
msgid ""
"Your request has already been submitted. Please refrain from resubmitting it."
msgstr "درخواست شما قبلا ثبت شده است لطفا از ارسال مجدد آن خودداری کنید."

#: .\fixplus\user\services\register.py:15
msgid "full_name"
msgstr "نام و نام خانوادگی"

#: .\fixplus\user\services\register.py:16
msgid "national_code"
msgstr "کد ملی"

#: .\fixplus\user\services\register.py:17
msgid "gender"
msgstr "جنسیت"

#: .\fixplus\user\services\register.py:18
msgid "address"
msgstr "آدرس"

#: .\fixplus\user\services\register.py:19
msgid "avatar"
msgstr "عکس پروفایل"

#: .\fixplus\user\services\register.py:20
msgid "identify_document_photo"
msgstr "تصویر کارت ملی/پاسپورت"

#: .\fixplus\user\services\register.py:25
msgid " cannot be None or empty."
msgstr " نمیتواند خالی باشد."

#: .\fixplus\user\services\skill.py:17
msgid "Skills can only be assigned to technician users."
msgstr "مهارت ها فقط می تواند به کاربران تکنسین اختصاص داده شود."

#: .\fixplus\user\services\skill.py:36
msgid "Error creating technician skill."
msgstr "ایجاد مهارت برای تکنسین با خطا مواحه شد."

#: .\fixplus\user\services\skill.py:58
msgid "Error update technician skill."
msgstr "بروزرسانی مهارت برای تکنسین با خطا مواحه شد."

#: .\fixplus\user\services\skill.py:70
msgid "Error delete technician skill."
msgstr "پاک کردن مهارت برای تکنسین با خطا مواحه شد."

#: .\fixplus\user\services\user.py:46
msgid "User was verified, please login."
msgstr "حساب شما وریفای شده است. لطفا وارد شوید."

#: .\fixplus\user\utils.py:36
msgid "Verification code is expired or invalid."
msgstr "کد اعتبارسنجی منقضی شده یا نامعتبر است."

#: .\fixplus\user\validators.py:11
msgid "password must include number"
msgstr "پسورد باید حتما شامل هدد باشد."

#: .\fixplus\user\validators.py:20
msgid "password must include letter"
msgstr "پسورد باید حتما شامل حروف باشد."

#: .\fixplus\user\validators.py:29
msgid "password must include special char"
msgstr "پسورد باید حتما شامل کارکترهای خاص باشد."

#~ msgid "You don't need to register."
#~ msgstr "شما نیازی به ثبت نام مجدد ندارید."
